# POST http://localhost:8080/form.html
# Transfer-Encoding: chunked
# Content-Type: application/json

# 5
# hello
# 7
# world!
# 0
POST http://localhost:8080/form.php HTTP/1.1
Transfer-Encoding: chunked
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="field1"
5
hello

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="field2"
7
hello22
------WebKitFormBoundary7MA4YWxkTrZu0gW



# POST http://localhost:8080/form.php  HTTP/1.1
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="name"

# Louise
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="email"

# loulou@gmail.com

# ------WebKitFormBoundary7MA4YWxkTrZu0gW

# GET http://localhost:8080/form.html


# POST http://localhost:8080/form.html HTTP/1.1
# Transfer-Encoding: chunked
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="field1"

# 5
# hello

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="field2"

# 7
# hello22
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--
# 0